name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install dependencies
        run: npm install

      - name: Build desktop app
        run: npm run build:desktop
        working-directory: apps/desktop

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/desktop
          tagName: ${{ github.ref_name }}
          releaseName: 'Toddy ${{ github.ref_name }}'
          releaseBody: |
            ## What's Changed

            See the full changelog and release notes for this version.

            ### Downloads
            - **Windows**: Download the `.msi` installer
            - **macOS**: Download the `.dmg` installer
            - **Linux**: Download the `.AppImage` or `.deb` package

            ---

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v0.0.0...${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

  create-release-notes:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          echo "# Release Notes for ${{ github.ref_name }}" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Changes" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md

      - name: Update release with changelog
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
